version: '3.9'

services:
  nasheMeDubaAnkhe:
    container_name: nasheMeDubaAnkhe
    image: postgres:13
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lovingEyesDatabase
    volumes:
      - pgdata:/var/lib/postgresql/data # <— persist data here
    networks:
      - loveNetwork

networks:
  loveNetwork:
    driver: bridge

volumes:
  pgdata: # <— named volume declared here
